// <auto-generated />
using System;
using Arcade.Data;
using Arcade.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arcade.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Arcade.Models.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasAnnotation("Sqlite:Autoincrement", true);

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT")
                    .HasDefaultValueSql("CURRENT_TIMESTAMP");

                b.Property<byte[]>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("BLOB");

                b.Property<byte[]>("PasswordSalt")
                    .IsRequired()
                    .HasColumnType("BLOB");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasMaxLength(40)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("UserName")
                    .IsUnique();

                b.ToTable("Users", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
